### ISSUE TITLE
How do I run the app on windows 8.1?

### ISSUE THREAD

**Issue by AlexanderBaggett** [tmcnab/Hyperglot#16]
So as it is mentioned in the documentation that Hyperglot runs on the node-webkit binary. So I downloaded that.  They have a page here on how to run apps.
https://github.com/rogerwang/node-webkit/wiki/How-to-run-apps

The problem is when I look at what I downloaded from Hyperglot. There is no .nw file to be found at all and the command line doesn't work. I am running windows 8.1

if I type nw (path to hyperglot folder) from CMD I get:
Cannot extract package 
Failed to unzip the package file: C:\Users\username

If I try to drag index.html to nw.exe I get this:
Cannot extract package 
Failed to unzip the package file: C:\Users\username\Desktop\Hyperglot-0.1.2\index.html

I even tried to make an app.nw file 
following these instructions

https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps

After making it and the package.nw
I tried to run it via dragging it to the nw.exe file 
I did not get an error, but instead got a blank white window and no web browser
interface.

**Comment by tmcnab** [comment]
I'll check that out later today on my 8.1 machine and get back to you.

**Comment by tmcnab** [comment]
@AlexanderBaggett so I just had a look now. I downloaded the [P1.2](https://github.com/tmcnab/Hyperglot/releases/tag/0.1.2) release `.nw` file and the windows `node-webkit` binary listed on their [github page](https://github.com/tmcnab/Hyperglot/releases/tag/0.1.2):

![image](https://cloud.githubusercontent.com/assets/2093059/3723085/193ad5c4-1670-11e4-8d02-6ffd23e98bec.png)

If you're talking about packaging it up yourself then you have to zip up the directory with the `package.json` in it and rename the extension of that zip file to `.nw`.

**Comment by AlexanderBaggett** [comment]
Okay, my bad totally. I was trying to run the source file. I will give that a try.
